# ==============================================================================
# Plane Helm Repository
# ==============================================================================

apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: makeplane
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.plane.so
